language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvtk5-dev libvtk5.8
  - sudo apt-get install -y libcgal-dev
compiler:
  - gcc
# Change this to your needs
script:
  - mkdir build
  - cd build
  - cmake ..
  - make

